### ISSUE TITLE
Regarding job opportunity at Microsoft.

### ISSUE THREAD

**Issue by Sudiptobanerjee123** [wrijugh/AskWriju#2]
Hello Sir, I am writing this to ask you whether the recruitment process of Microsoft has opened and if you can recommend me to an opening so that I can be interviewed for the following position. I am currently a final year undergraduate student, with no full-time experiences but a total of 1 year of Internship experiences. During the process, I have worked with Android Studio and Machine Learning. 

My experience is the only huddle that is not letting me into any job opportunity, I have expertise in AWS Cloud Architect and have deployed my own portfolio using Route 53. Link:- sudiptabanerjee.tech

I hope to hear from you soon.
Thanks
Sudipta

**Comment by wrijugh** [comment]
Please have a check https://careers.microsoft.com/. I recommend that you create a profile and upload your resume. Based on location and keyword you can create alert. This will send you new jobs.

**Comment by Sudiptobanerjee123** [comment]
Hello Sir, I did apply to few positions but haven't heard yet. I wanted to ask whether I can be a fit under your supervision?

Thanks 
Sudipta
