### ISSUE TITLE
Looking for Hands on Practice - Azure Administrator

### ISSUE THREAD

**Issue by arijit-in** [wrijugh/AskWriju#3]
I am currently working as a Technical support analyst, deal in troubleshooting OS issues for Windows and Mac, I am willing to shift my career to the cloud hence started the journey. I have prepared for az 900 and have scheduled an exam for the end of July, I have started with az 103 preparation and trying to explore the Azure Portal resources.

I actually wanted to know if there is a way to get a hands-on experience similar to live projects and gauge my knowledge while I am doing the course.

If there are any modules with To_Do kind of topics where there are tasks given to be completed, that would be of great help.

**Comment by wrijugh** [comment]
You may try the Azure for free https://azure.microsoft.com/en-us/free/
